### ISSUE TITLE
Noisy runs

### ISSUE THREAD

**Issue by vemv** [fulcrologic/fulcro-spec#11]
Hi!

I see the following when running `(clojure.test/run-all-tests #"(foo)\..*")` in-repl:

![image](https://user-images.githubusercontent.com/1162994/52536040-f8bb3800-2d55-11e9-973c-a5720552e394.png)

Seems an unnecessary output. Is it possible to disable it?

Using `fulcrologic/fulcro-spec "2.0.2-1"`.

Thanks - Victor

**Comment by awkay** [comment]
This basically explains what is happening, and should give you ideas about how you could set up your env to mute them if you want to run tests that way:

https://github.com/lambdaisland/kaocha/issues/15

**Comment by vemv** [comment]
I tried 2.1.3 which you point out in that thread as a possible solution. Didn't work though!

In any case I'm not sure users should be the ones responsible for cleaning up a particular libraries' output.

(For clarity, in my test suite I use a mixture of clojure.test tests and fulcro-spec tests)
