### ISSUE TITLE
Introduce indentation specification for macros

### ISSUE THREAD

**Issue by thenonameguy** [fulcrologic/fulcro-spec#12]
See: https://cider.readthedocs.io/en/latest/indent_spec/
Currently CIDER formats the code in an unwanted way:
```clojure
    (behavior "failure retry"
              (when-mocking ...))
```

After further investigation introducing these won't solve my immediate problem until [this cljfmt issue](https://github.com/weavejester/cljfmt/issues/49) get's resolved.

**Comment by awkay** [comment]
If you have a PR That you want to submit to solve a problem, and it doesn't adversely affect others, please submit it.

**Comment by thenonameguy** [comment]
I don't have a PR (yet), I submitted this issue as a possibly enhancement to the library if someone wants to allocate time to it. I think having a community approved description of how a macro treats it's arguments syntactically and having it centralized in code alongside would be a nice addition. I watched your awesome Fulcro videos and in them it seems you use Cursive's indentation settings so they show up correctly. It would be great if we could standardize on something uniform so people don't have to do the same in their editor manually.

This wouldn't be a huge change ([I think most of it would boil down to metadata like this](https://github.com/metosin/compojure-api/blob/85738b802c7f150f4f550ffca91a4782c75f8091/src/compojure/api/core.clj#L27)) I'll consider adding it over the weekend.

**Comment by awkay** [comment]
Sure, I just don't leave open issues that are requests for "me or some random person" to do work.  If someone has a contribution, a PR is great.

**Comment by vemv** [comment]
I've used these for a while successfully:

```
    fulcro-spec.core/specification -> {:style/indent 1}
    fulcro-spec.core/behavior -> {:style/indent 1}
    fulcro-spec.core/assertions -> {:style/indent 0}
```

Under my setup I just alter var metadata so I don't need a PR, because I'd rather not open something I'm not gonna use.
