### ISSUE TITLE
Incompatible event key :expected for clojure.test/report 

### ISSUE THREAD

**Issue by pithyless** [fulcrologic/fulcro-spec#13]
`clojure.test` reporters depend on an event map to pretty-print failures. For an assertion that macro-expands to `(is (= :foo :bar))`, Fulcro Spec is returning `{:expected :foo}` instead of `{:expected '(= :foo :bar)}`. This is a problem for any reporters that do not just print the error, but try to analyze it further (e.g. Kaocha that tries to pretty-print data diffs).

More details:

https://github.com/clojure/clojure/blob/28efe345d5e995dc152a0286fb0be81443a0d9ac/src/clj/clojure/test.clj#L221

https://github.com/lambdaisland/kaocha/blob/ac234e866e81514313beaa8da917665e99cd1b65/src/kaocha/report.clj#L215-L220

Maybe a workaround is to return the full expression in `:expected` and use a different key for the expected-value that is used by the Fulcro reporters?

**Comment by awkay** [comment]
Yeah, this was written a very long time ago...sounds like we need to get a sample of what noramlly gets sent in the various possible clj test cases, and then use :fulcro-spec/expected for our formatting.

**Comment by Pancia** [comment]
I've made a branch to try to fix this: https://github.com/fulcrologic/fulcro-spec/tree/issue/13

**Comment by pithyless** [comment]
Testing with:

```
(specification "testing"
  (assertions
    1 => 2))
```

Output with fulcro-spec 3.1.4

``` 
       ASSERTION:

       1
       =>
       2

          Actual: 1
        Expected: 2
```

Output with current branch:

```
       ASSERTION:

       1 => 2

         Actual:	"nil"
       Expected:	"nil"
```

**Comment by Pancia** [comment]
@pithyless just pushed a commit, should be fixed now

**Comment by pithyless** [comment]
I can confirm the `nil` issue is fixed with the new commit.

Unfortunately, the Fulcro Spec reporter is still not very usable with Kaocha, because it does not report compiler runtime errors. For example, if you comment out a var, you will see this in clojure.test:

```
Failed reloading ns: ...
Exception: clojure.lang.Compiler$CompilerException: Syntax error compiling at (...:16:29).
#:clojure.error{:phase :compile-syntax-check, :line 16, :column 29, :source "..."}
...
Caused by: java.lang.RuntimeException: No such var: ...
```

With the fulcro-spec reporter, all I see is:

```
[watch] Error reloading, all tests skipped.
```

I have not dug into the code, so I am unsure where the problem is. Just submitting a experience report for now. :)
