### ISSUE TITLE
fulcro-report reports twice the number of failures / oks 

### ISSUE THREAD

**Issue by MrEbbinghaus** [fulcrologic/fulcro-spec#18]
The fulcro-report reports twice the number of assertions.

Example: 

```clojure
(deftest foo
  (is false))
 ```

default koacha reporter
```
1 tests, 1 assertions, 1 failures.
```

fulcro-spec.reporters.terminal/fulcro-report:
```
Ran 1 tests containing 2 assertions.
2 failures, 0 errors.
```

Same for assertions that do not fail.

**Comment by awkay** [comment]
@Pancia is working on this library this week, perhaps we'll see what the problem is here as well. Thanks for the note.

**Comment by awkay** [comment]
We're probably not going to maintain the terminal reporter, since kaocha now has a document-based reporter that works well enough for CI.  You're welcome to look into it...it's really not a lot of code.
